BoreholeMVCUI/Models/BoreholeType.cs
namespace BoreholeMVCUI.Models
{
    public enum BoreholeType
    {
        Basic,
        Cable,
        Drill
    }
}

BoreholeMVCUI/Models/BoreholeViewModel.cs
using BoreholeMVCUI.Models.Enums;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BoreholeMVCUI.Models
{
    public class BoreholeViewModel
    {
        [DisplayName("ID")]
        public int Id { get; set; }

        [DisplayName("X Position")]
        [Required(ErrorMessage = "This field is required")]
        public int? X { get; set; }

        [DisplayName("Y Position")]
        [Required(ErrorMessage = "This field is required")]
        public int? Y { get; set; }

        [DisplayName("Depth")]
        [Range(0, 500)]
        [Required(ErrorMessage = "This field is required")]
        public decimal? Depth { get; set; }

        public BoreholeType BoreholeType { get; set; }
    }
}

BoreholeMVCUI/Models/CableViewModel.cs
using BoreholeData.Entities;
using BoreholeData.Enums;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BoreholeMVCUI.Models
{
    public class CableViewModel : BoreholeViewModel
    {
        public CableViewModel()
        {
                
        }

        public CableViewModel(CableBorehole borehole)
        {

            this.Id = borehole.ID;
            this.X = borehole.X;
            this.Y = borehole.Y;
            this.Depth = borehole.Depth;
            this.CableType = borehole.CableType;
            this.CableStrength = borehole.CableStrength;
        }

        [DisplayName("Cable Type")]
        [Required]
        public CableType CableType { get; set; }


        [DisplayName("Cable Strength")]
        [Required]
        public string CableStrength { get; set; }
    }
}

BoreholeMVCUI/Models/DrillViewModel.cs
using BoreholeData.Entities;
using BoreholeData.Enums;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BoreholeMVCUI.Models
{
    public class DrillViewModel : BoreholeViewModel
    {
        public DrillViewModel()
        {
            
        }
        public DrillViewModel(DrillBorehole borehole)
        {
            this.Id = borehole.ID;
            this.X = borehole.X;
            this.Y = borehole.Y;
            this.Depth = borehole.Depth;
            this.DrillType = borehole.DrillType;
            this.DrillStrength = borehole.DrillStrength;
        }

        [DisplayName("Drill Type")]
        [Required]
        public DrillType DrillType { get; set; }


        [DisplayName("Drill Strength")]
        [Required]
        public string DrillStrength { get; set; }
    }
}

BoreholeMVCUI/Models/Enums/BoreholeType.cs
namespace BoreholeMVCUI.Models.Enums
{
    public enum BoreholeType
    {
        Basic,
        Cable,
        Drill
    }
}

BoreholeMVCUI/Models/ErrorViewModel.cs
namespace BoreholeMVCUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BoreholeMVCUI/Controllers/BoreholeController.cs
using BoreholeData;
using BoreholeData.Entities;
using BoreholeData.Repositories;
using BoreholeMVCUI.Models;
using BoreholeMVCUI.Models.Enums;
using Microsoft.AspNetCore.Mvc;

namespace BoreholeMVCUI.Controllers
{
    public class BoreholeController : Controller
    {
        private BoreholeRepository repository;

        public BoreholeController(BoreholeContext context, ILogger<BoreholeRepository> log)
        {
            repository = new BoreholeRepository(context, log);
        }

        public IActionResult Index()
        {
            var allBoreholes = repository.GetAll().Select(bh => new BoreholeViewModel() { Id = bh.ID, X = bh.X, Y = bh.Y, Depth = bh.Depth, BoreholeType = (bh.GetType() == typeof(CableBorehole) ? BoreholeType.Cable : (bh.GetType() == typeof(DrillBorehole) ? BoreholeType.Drill : BoreholeType.Basic)) }).ToList();

            ViewBag.ShowMap = true;

            return View(allBoreholes);
        }

        [Route("borehole/GetByArea/{x1}/{y1}/{x2}/{y2}")]
        public IActionResult GetByArea(int x1, int y1, int x2, int y2)
        {
            var boreholes = repository.GetByArea(x1,y1,x2,y2).Select(bh => new BoreholeViewModel() { Id = bh.ID, X = bh.X, Y = bh.Y, Depth = bh.Depth, BoreholeType = (bh.GetType() == typeof(CableBorehole) ? BoreholeType.Cable : (bh.GetType() == typeof(DrillBorehole) ? BoreholeType.Drill : BoreholeType.Basic)) }).ToList();

            ViewBag.ShowMap = false;

            return View("Index", boreholes);
        }

        public IActionResult Details(int id)
        {
            var borehole = repository.GetById(id);

            if (borehole.GetType() == typeof(CableBorehole))
                return View("CableView", new CableViewModel((CableBorehole)borehole));
            else if (borehole.GetType() == typeof(DrillBorehole))
                return View("DrillView", new DrillViewModel((DrillBorehole)borehole));

            return RedirectToAction("Index");
        }

        public IActionResult AddCable()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCable(CableViewModel model)
        {
            if (ModelState.IsValid)
            {
                repository.Add(new CableBorehole() { Depth = (decimal)model.Depth, X = (int)model.X, Y = (int)model.Y, CableStrength = model.CableStrength, CableType = model.CableType });

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult AddDrill()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDrill(DrillViewModel model)
        {
            if (ModelState.IsValid)
            {
                repository.Add(new DrillBorehole() { Depth = (decimal)model.Depth, X = (int)model.X, Y = (int)model.Y, DrillStrength = model.DrillStrength, DrillType = model.DrillType });

                return RedirectToAction("Index");
            }

            return View();
        }

        [Route("borehole/delete/{id}")]
        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

BoreholeMVCUI/Controllers/HomeController.cs
using BoreholeMVCUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BoreholeMVCUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BoreholeMVCUI/Views/Borehole/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model BoreholeViewModel
@{
    ViewData["Title"] = "Add Borehole";
}
@using (Html.BeginForm()) {
    <table>
        <tr>
            <td>@Html.DisplayNameFor(i => i.X)</td>
            <td>@Html.TextBoxFor(i => i.X)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.X)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Y)</td>
            <td>@Html.TextBoxFor(i => i.Y)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Y)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Depth)</td>
            <td>@Html.TextBoxFor(i => i.Depth)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Depth)</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
    @Html.ActionLink("Go Back to Borehole List", "Index")
}

BoreholeMVCUI/Views/Borehole/AddCable.cshtml
@using BoreholeData.Enums
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CableViewModel
@{
    ViewData["Title"] = "Add Cable Borehole";
}
@using (Html.BeginForm()) {
    <h5>Add Cable Borehole</h5>
    <table class="AddTable">
        <tr>
            <td>@Html.DisplayNameFor(i => i.X)</td>
            <td>@Html.TextBoxFor(i => i.X)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.X)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Y)</td>
            <td>@Html.TextBoxFor(i => i.Y)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Y)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Depth)</td>
            <td>@Html.TextBoxFor(i => i.Depth)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Depth)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.CableType)</td>
            <td>@Html.DropDownListFor(i => i.CableType, Html.GetEnumSelectList(typeof(CableType)))</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.CableType)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.CableStrength)</td>
            <td>@Html.TextBoxFor(i => i.CableStrength)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.CableStrength)</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
    <br />
    @Html.ActionLink("Go Back to Borehole List", "Index")
}

BoreholeMVCUI/Views/Borehole/AddDrill.cshtml
@using BoreholeData.Enums
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DrillViewModel
@{
    ViewData["Title"] = "Add Drill Borehole";
}
@using (Html.BeginForm())
{
    <h5>Add Drill Borehole</h5>
    <table class="AddTable">
        <tr>
            <td>@Html.DisplayNameFor(i => i.X)</td>
            <td>@Html.TextBoxFor(i => i.X)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.X)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Y)</td>
            <td>@Html.TextBoxFor(i => i.Y)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Y)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.Depth)</td>
            <td>@Html.TextBoxFor(i => i.Depth)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.Depth)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.DrillType)</td>
            <td>@Html.DropDownListFor(i => i.DrillType, Html.GetEnumSelectList(typeof(DrillType)))</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.DrillType)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(i => i.DrillStrength)</td>
            <td>@Html.TextBoxFor(i => i.DrillStrength)</td>
            <td class="errorMessage">@Html.ValidationMessageFor(i => i.DrillStrength)</td>
        </tr>
    </table>
    <input type="submit" value="Save" />
    <br/> 
    @Html.ActionLink("Go Back to Borehole List", "Index")
}

BoreholeMVCUI/Views/Borehole/CableView.cshtml
@model CableViewModel
@{
    ViewData["Title"] = "Cable Borehole " + Model.Id;
}
<h5>Cable Borehole Details</h5>
<table class="ViewTable">
    <tr>
        <td>@Html.DisplayNameFor(i => i.Id)</td>
        <td>@Html.DisplayFor(i => i.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.X)</td>
        <td>@Html.DisplayFor(i => i.X)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Y)</td>
        <td>@Html.DisplayFor(i => i.Y)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Depth)</td>
        <td>@Html.DisplayFor(i => i.Depth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.CableType)</td>
        <td>@Html.DisplayFor(i => i.CableType)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.CableStrength)</td>
        <td>@Html.DisplayFor(i => i.CableStrength)</td>
    </tr>
</table>
@Html.ActionLink("Go Back to Borehole List", "Index")

BoreholeMVCUI/Views/Borehole/DrillView.cshtml
@model DrillViewModel
@{
    ViewData["Title"] = "Drill Borehole " + Model.Id;
}
<h5>Drill Borehole Details</h5>
<table class="ViewTable">
    <tr>
        <td>@Html.DisplayNameFor(i => i.Id)</td>
        <td>@Html.DisplayFor(i => i.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.X)</td>
        <td>@Html.DisplayFor(i => i.X)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Y)</td>
        <td>@Html.DisplayFor(i => i.Y)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.Depth)</td>
        <td>@Html.DisplayFor(i => i.Depth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.DrillType)</td>
        <td>@Html.DisplayFor(i => i.DrillType)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(i => i.DrillStrength)</td>
        <td>@Html.DisplayFor(i => i.DrillStrength)</td>
    </tr>
</table>
@Html.ActionLink("Go Back to Borehole List", "Index")

BoreholeMVCUI/Views/Borehole/Index.cshtml
@using BoreholeMVCUI.Models.Enums
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<BoreholeViewModel>
@{
    ViewData["Title"] = "Borehole List";
}
<div class="container">
    <div class="row">
        <div class="col">
            <div id="AddBoreholeButton" class="btn btn-outline-primary">@Html.ActionLink("Add Cable Borehole", "AddCable")</div>
            <div id="AddBoreholeButton" class="btn btn-outline-primary">@Html.ActionLink("Add Drill Borehole", "AddDrill")</div>
            <div id="BoreholeData" class="">
                <table class="BoreholeTableGrid">
                    <thead>
                        <tr>
                            <td>Type</td>
                            <td>@Html.DisplayNameFor(bh => bh.FirstOrDefault().Id)</td>
                            <td>@Html.DisplayNameFor(bh => bh.FirstOrDefault().X)</td>
                            <td>@Html.DisplayNameFor(bh => bh.FirstOrDefault().Y)</td>
                            <td>@Html.DisplayNameFor(bh => bh.FirstOrDefault().Depth)</td>
                            <td>Options</td>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (BoreholeViewModel vm in Model)
                    {
                        <tr onclick="location.href = '@Url.Action("Details", "Borehole", new { id=vm.Id })'">
                            @if(vm.BoreholeType == BoreholeMVCUI.Models.Enums.BoreholeType.Cable)
                            {
                                <td><i class="fa-solid fa-bore-hole"></i></td>
                            }
                            else if (vm.BoreholeType == BoreholeMVCUI.Models.Enums.BoreholeType.Drill)
                            {
                                <td><i class="fa-solid fa-arrows-down-to-line"></i></td>
                            }
                            else
                            {
                                <td><i class="fa-solid fa-ring"></i></td>
                            }
                            <td>@Html.DisplayFor(bh => vm.Id)</td>
                            <td>@Html.DisplayFor(bh => vm.X)</td>
                            <td>@Html.DisplayFor(bh => vm.Y)</td>
                            <td>@Html.DisplayFor(bh => vm.Depth)</td>
                            <td onClick='event.stopPropagation();'><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-id="@vm.Id">Delete</button></td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
        @if (ViewBag.ShowMap)
        {
            <div class="col" id="map">
                @await Html.PartialAsync("_Map", Model)
            </div>
        }
        else
        {
            @Html.ActionLink("Back to Index", "Index")
        }
    </div>
</div>
<div id="deleteModal" class="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Delete Borehole</h5>
            </div>
            <div class="modal-body">
                <div id="deleteMessage">Are you sure you want to delete this borehole?</div>
            </div>
            <div class="modal-footer">
                <button type="button" id="deleteButton" class="btn btn-primary">Delete</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var modal = $("#deleteModal");
        modal.on('show.bs.modal', function (event) {

            var button = event.relatedTarget;
            var boreholeId = button.getAttribute('data-bs-id');

            var modalMessage = "Are you sure you want to delete borehole with ID " + boreholeId;
            modal.find(".modal-body #deleteMessage").text(modalMessage);
            modal.find(".modal-footer #deleteButton").on("click", function () { location.href = "@Url.Action("Delete", "Borehole")/" + boreholeId; });
        });

        modal.on('hide.bs.modal', function (event) {
            modal.find(".modal-footer #deleteButton").unbind('click');
        });

        @{
            int? maxX = Model.Count() > 0 ? Model.Max(i => i.X) : 0;
            int? maxY = Model.Count() > 0 ? Model.Max(i => i.Y) : 0;

            decimal? factor = 0;
            if (maxX > 0 && maxY > 0)
            {
                factor = 500 / (maxX < maxY ? maxY : maxX);
            }
        }

        var start = null;
        var startCoord = null;

        function draw() {
            const canvas = $("#canvasMap");
            if (canvas[0].getContext) {
                const ctx = canvas[0].getContext("2d");

                ctx.fillStyle = "blue";
                @foreach (BoreholeViewModel viewModel in Model)
                {
                    <text>
                            ctx.beginPath();
                            ctx.arc(@(viewModel.X * factor), @(500 - (viewModel.Y * factor)), 5, 0, 2 * Math.PI);
                            ctx.fill();
                    </text>
                }

                const render = (e) => {
                    if (start) drawBox(e);
                }

                const drawBox = (e) => {
                    ctx.clearRect(start.x, start.y, e.offsetX - start.x, e.offsetY - start.y);
                    ctx.strokeRect(start.x, start.y, e.offsetX - start.x, e.offsetY - start.y);
                };

                canvas[0].onmousedown = e => { start = { x: e.offsetX, y: e.offsetY }; startCoord = { x: Math.floor(e.offsetX / @factor), y: Math.floor((500 - e.offsetY) / @factor) }; };
                canvas[0].onmouseup = e => {
                    var endX = Math.floor(e.offsetX / @factor);
                    var endY = Math.floor((500 - e.offsetY) / @factor);
                    var loc = `@Url.Action("GetByArea", "Borehole")/${startCoord.x}/${startCoord.y}/${endX}/${endY}`;

                    window.location.href = loc;
                }
                canvas[0].onmousemove = render;
            }
        }

        $(document).ready(draw());

    </script>
}

BoreholeMVCUI/Views/Borehole/_Map.cshtml
@model IEnumerable<BoreholeViewModel>
@{
    <canvas id="canvasMap"
            width="500" height="500">
    </canvas>
}

BoreholeMVCUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BoreholeMVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoreholeManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoreholeMVCUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Borehole Manager</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Borehole Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>